[versions]
gradle-publish = "1.3.0"

proguard = "7.6.0"

[plugins]
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish" }

[libraries]
proguard = { group = "com.guardsquare", name = "proguard-gradle", version.ref = "proguard" }
proguard-annotations = { group = "com.guardsquare", name = "proguard-annotations", version.ref = "proguard" }

[bundles]
proguard = ["proguard", "proguard-annotations"]
